[build]
functions = "netlify/functions"

[functions]
# Tell Netlify to use the Python runtime for functions
node_bundler = "esbuild"
python_version = "3.9"

[functions."netlify/functions"]
# Specify the path to your Python dependencies file
external_packages = ["requests", "firebase-admin"]
